from enum import IntEnum
from typing import NamedTuple

class Event(NamedTuple):
    wd: int
    mask: int
    cookie: int
    name: str

class INotify:
    fd: int
    def __init__(self, inheritable: bool = ..., nonblocking: bool = ..., closefd: bool = ...) -> None: ...
    def add_watch(self, path: str, mask: int) -> int: ...
    def rm_watch(self, wd: int) -> None: ...
    def read(self, timeout: int | None = ..., read_delay: int | None = ...) -> list[Event]: ...
    def close(self) -> None: ...
    def fileno(self) -> int: ...

class flags(IntEnum):
    ACCESS = ...
    MODIFY = ...
    ATTRIB = ...
    CLOSE_WRITE = ...
    CLOSE_NOWRITE = ...
    OPEN = ...
    MOVED_FROM = ...
    MOVED_TO = ...
    CREATE = ...
    DELETE = ...
    DELETE_SELF = ...
    MOVE_SELF = ...
    UNMOUNT = ...
    Q_OVERFLOW = ...
    IGNORED = ...
    ONLYDIR = ...
    DONT_FOLLOW = ...
    EXCL_UNLINK = ...
    MASK_ADD = ...
    ISDIR = ...
    ONESHOT = ...
    @classmethod
    def from_mask(cls, mask: int) -> list[flags]: ...

class masks(IntEnum):
    CLOSE = ...
    MOVE = ...
    ALL_EVENTS = ...
